[project]
authors = ["Łukasz Kalbarczyk"]
entry = "redstone_core.sw"
forc-version = "0.63.6"
license = "Apache-2.0"
name = "redstone_core"
organization = "RedStone"

[dependencies]
redstone = { path = "../redstone-fuel-sdk" }
